development:
  adapter: mysql2
  database: activity_development
  host: localhost
  username: root
  password: mxing~1228
test:
  adapter: mysql2
  database: activity_test
  host: localhost
  username: root
  password: mxing~1228

production:
  adapter: mysql2
  database: activity_production
  host: localhost
  username: root
  password: mxing~1228